### ISSUE TITLE
Ticketing - In the edit event UI, the save button should update the event and all showings

### ISSUE THREAD

**Issue by ben16williams** [WonderTix/WonderTix#151]

**Comment by samkhodak** [comment]
Events and showings are updated correctly, but ticket types are still not edited correctly and they disappear when trying to save an edit on them.

There is a [branch](https://github.com/WonderTix/WonderTix/tree/julian-final-merge) that has begun to address these issues, but it has bugs. Feel free to continue on that one or start a branch from scratch.

**Comment by jgreever** [comment]
Branch provided doesn't exist: https://github.com/WonderTix/WonderTix/tree/julian-final-merge (presents a 404 error). Only `main` and `ticketing` branches exist. Moving this back to backlog as it is no longer available for us to use and we will have to start from scratch.
