### ISSUE TITLE
Database - Foreign columns should not have names that include 'fk' or 'id'.

### ISSUE THREAD

**Issue by samkhodak** [WonderTix/WonderTix#268]

**Comment by ben16williams** [comment]
A good number of sources report best practice is for foreign keys to be something like `fk_<targetTable>_<sourceTable>` https://www.dotnettricks.com/learn/sqlserver/sql-server-naming-conventions-and-standards

It looks like most fk in wondertix currently have the foreign key format `<targetTable>_fk` which is pretty close and still helps with readability
