### ISSUE TITLE
Setup countertop payment reader integration

### ISSUE THREAD

**Issue by ben16williams** [WonderTix/WonderTix#384]
PPH will need to be able to use countertop payment readers to sell tickets at the door. To do this, they will purchase some[ readers provided by Stripe](https://stripe.com/docs/terminal/readers/bbpos-wisepos-e). Stripe provides APIs to interact with these readers which will need to be integrated with. There are some docs to setup the integration [here](https://stripe.com/docs/terminal/payments/setup-integration?terminal-sdk-platform=server-driven), as well as instructions to connect to a simulated reader to test out the integration [here](https://stripe.com/docs/terminal/payments/connect-reader). It sounds like these readers send processed payment responses to a webhook, so the existing webhook may be able to be reused.

**Comment by ReidLuttrell** [comment]
Send to card reader option is added to the Admin purchase page, there you can fill you cart, select reader by ID, and press the send to card reader button. This will send the order as a payment intent through stripe, and add the order to the database. To do this two API functions were made, "event/reader-checkout", which does the payment intent and database work, and "orders/readers" which retrieves a list of the readers attached to the stripe key. Currently work in progress is listening for payment success conditions and communicating this back to the front end, which will be needed when the physical card readers are in use. We are working on a reader purchase page which will be redirected to and poll the stripe api for payment success.

**Comment by ReidLuttrell** [comment]
Reader purchase page is created and mostly implemented. Websocket is connected to send payment status to this page from the server. Last things to do are safely implementing the websocket cert, and handling order cancels and payment failures.
