### ISSUE TITLE
Database - Site encounters 15 duplicates of showings

### ISSUE THREAD

**Issue by PhayC** [WonderTix/WonderTix#386]
when selecting a ticket to see showings, webpage throws an error about encountering two duplicate keys for that showing, 15 times. it seems like its correlates to the number of showings represented in the created JSON event card
![image](https://github.com/WonderTix/WonderTix/assets/131018407/31bbc4c9-37b1-48af-811d-597b35088104)
![image](https://github.com/WonderTix/WonderTix/assets/131018407/8066bc28-2f6d-481e-a45a-3a82c5f52ba7)

**Comment by henrykaus** [comment]
This was fixed with [Pull Request TIC-102](https://github.com/WonderTix/WonderTix/pull/412)
