### ISSUE TITLE
Ticketing - Resize image in Admin Events and Admin Season Page properly

### ISSUE THREAD

**Issue by henrykaus** [WonderTix/WonderTix#443]
The image in the Admin Events Page and Admin Seasons Page should resize responsively to the size of the page. Currently it is taking up an odd amount of space, and does not respond to the current screen size.

![image](https://github.com/WonderTix/WonderTix/assets/92124260/89644431-1c2b-4972-919f-858050ada7af)

**Comment by omariio1000** [comment]
Seems to me to be fixed. Had to just remove the max width. Responds to size of the window.

<img width="1176" alt="image" src="https://github.com/WonderTix/WonderTix/assets/43871473/c1273f8e-8a92-42aa-9bc5-1b0d882b6fe4">
