### ISSUE TITLE
Ticketing - Concessions Tickets should be repurposed for Fees

### ISSUE THREAD

**Issue by henrykaus** [WonderTix/WonderTix#444]
When attempting to purchase a concessions ticket, the functionality is inconsistent and does not show up properly in Stripe. Teams should communicate with Portland Playhouse and/or Ben to understand how this feature should work and fix it.

**Comment by ben16williams** [comment]
Whether or not concessions on tickets are needed is TDB by PPH. They may either be removed entirely or repurposed as a way to include ticket fees.

**Comment by ben16williams** [comment]
Concessions should be renamed to fees and the fee should be visible when purchasing a ticket
