### ISSUE TITLE
Contacts page missing information

### ISSUE THREAD

**Issue by henrykaus** [WonderTix/WonderTix#516]
When looking at a contact, there are several fields that do not show information. There are also many UI issues (especially on a mobile-screen size) with lacks of spacing.

This is correct (although the Donorbadge field is blank):
![image](https://github.com/WonderTix/WonderTix/assets/92124260/2b799d16-0dde-4fea-bbee-fc8085de1561)

After clicking `Show All Information`, the address is missing:
![image](https://github.com/WonderTix/WonderTix/assets/92124260/736a8161-a1ce-412b-b93b-6418b9f03ed7)

The spacing on the side of the screen should mimic other areas of the admin panels (i.e. reduce the left-right margins):
![image](https://github.com/WonderTix/WonderTix/assets/92124260/4d4b3243-800b-4232-8e65-f1ac431c2ecb)

The order date and times should be formatted in a readable manner and there should be a gap between the order cards:
![image](https://github.com/WonderTix/WonderTix/assets/92124260/14402d20-a93d-4abb-922a-e9da75b7ef08)

Also, if a contact doesn't have any orders, the message below should be a little less cryptic, something like `<person> hasn't made any orders.`.
![image](https://github.com/WonderTix/WonderTix/assets/92124260/f7ce85d2-d18d-4ca6-a2c9-0d904b932500)

The Refund button is also non-functional. Although, this should be discussed with the sponsor if they should be able to refund right from here, rather than just from the working Refund page.

**Comment by ben16williams** [comment]
This is a high priority. The refund page is sufficient for now and we can remove the refund button from this order view.

**Comment by ben16williams** [comment]
Showing all information for a contact should also show donations that they've made and the order information should be expanded to include all the items included in the order (showings, events, seasons, etc)
