### ISSUE TITLE
Inspect payment_intent after checkout session completes

### ISSUE THREAD

**Issue by ben16williams** [WonderTix/WonderTix#577]
Seems like we'll probably want to check the status of the `payment_intent` after receiving a `checkout.session.completed` event from Stripe and update the order in Wondertix accordingly because a completed checkout session does not always mean that the payment was successful. https://stripe.com/docs/payments/payment-intents/verifying-status

**Comment by benfaustin95** [comment]
I think a `checkout.session.completed ` event is only fired if the payment_intent was successful.

**Comment by ben16williams** [comment]
Are there Stripe docs that say that somewhere? This [Check PaymentIntent status on the client without using confirmCardPayment](https://stripe.com/docs/payments/payment-intents/verifying-status#checking-status-retrieve) table is what made me create this task, and I couldn't find anything that explicitly says that `checkout.session.completed` is only sent if the payment succeeds

**Comment by ben16williams** [comment]
I think you're probably right but the only source I could find that describes that exactly is from this stackoverflow post https://stackoverflow.com/questions/62882815/when-does-checkout-session-completed-trigger. I wish Stripe's docs were a little more clear on this but it sounds like the safe assumption is that a checkout.session.completed is only sent if the payment_intent succeeds, but that other payment_intent events get sent for failed payments or incomplete payments that happen on the checkout page

**Comment by ben16williams** [comment]
I was actually able to confirm that is that case with some test credit cards that fail payment. Here is the failed transaction where the checkout session timed out https://dashboard.stripe.com/test/payments/pi_3OaBOJL95zqXUSVM08FVbLGE
