### ISSUE TITLE
Create and refactor user admin-page navigation

### ISSUE THREAD

**Issue by henrykaus** [WonderTix/WonderTix#624]
This ticket encompasses a few different aspects:

* Within WonderTix, there are 2 separate but identical nav components used in the admin panels
* There should instead be just one parent component that creates the structure of the Navigation, and then can be customized to suit the admin page
* There are (at least) 2 admin top-bar components when there should instead be 1 reusable one.

**Comment by nateruble** [comment]
User story: As a client, I want the navigation drop downs to work and the navigation bars and website to be elegantly designed for ease of performance and less chance of myself experiencing bugs.
