### ISSUE TITLE
Update sold out Indicator to reference Ticket Restriction level availability

### ISSUE THREAD

**Issue by benfaustin95** [WonderTix/WonderTix#640]
Currently the sold out indicators reference available seats at the event instance level, thus if a show has available seats but no available ticket restrictions it will not be marked as sold out but rather will result in an empty ticket type select.

**Comment by henrykaus** [comment]
The sold out indicator will need to be based upon both the `available seats` and `ticket restriction availability` opting for the lesser of the two. If there are 120 available ticket restrictions but only 100 available seats, only 100 tickets should be sold. And if only 100 ticket restrictions and 120 available seats, also only 100 tickets should be sold.
