### ISSUE TITLE
Remove references to Portland Playhouse

### ISSUE THREAD

**Issue by ben16williams** [WonderTix/WonderTix#659]
With the multi-tenancy design for supporting different companies, Wondertix is more of it's own application that is separate from PPH. 

Generify the webpage by removing any reference to PPH (the back drop on the main page also needs to be removed/replaced)

Generify the codebase from any references to PPH or write follow up stories to do so.

**Comment by baylie-r-g** [comment]
Would we need to create a WonderTix logo to replace the PPH one?

**Comment by ben16williams** [comment]
Shouldn't be necessary but would be cool if you're feeling creative!

**Comment by baylie-r-g** [comment]
Literally started working on one while waiting for an answer

**Comment by baylie-r-g** [comment]
![WTix logo](https://github.com/WonderTix/WonderTix/assets/126998719/e9c59c82-8bc6-4802-8cd9-514c6ea2ddb4)
Not exactly professional quality but it should make a solid placeholder

**Comment by baylie-r-g** [comment]
Do I need to get rid of the Copyright statement in the footer, or does it need to stay?

**Comment by ben16williams** [comment]
Let's keep the copyright statement for now
